version: '3.4'

networks:
    myAppNetwork: 

services:
  inventoryserivce:
    image: ${DOCKER_REGISTRY-}inventoryserivce
    mem_limit: 1024M
    build:
      context: .
      dockerfile: InventorySerivce/Dockerfile
    depends_on:
        - SqlServerDb

  SqlServerDb:
    container_name: SqlServerContainer
    image: mcr.microsoft.com/mssql/server:2017-latest
    mem_limit: 2048M
    ports:
        - 1433:1433
    environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=YourStrong@Passw0rd 
