namespace InventorySerivce.Models
{
    public class Item
    {
        public long Id { get; set; }

        //Id generated by Steam
        public long SteamId { get; set; }

        //Steam64Id
        public long OwnerId { get; set; }

        //Steam64Id
        public long BotId { get; set; }
        public Bot Bot { get; set; }

        public int SkinId { get; set; }
        public Skin Skin { get; set; }

        public float Wear {  get; set; }

        public float Price { get; set; }
        public DateTime? Tradeable { get; set; }
    }
}
